# Generated by Django 5.1.2 on 2024-10-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/image/cars/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.FloatField(blank=True, null=True, verbose_name='Объем двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_power',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мощность двигателя'),
        ),
    ]
