# Generated by Django 5.1.2 on 2024-10-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_image_alter_car_engine_alter_car_engine_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/cars', verbose_name='Фото'),
        ),
    ]
